### ISSUE TITLE
Compilation error on Mac OS

### ISSUE THREAD

**Issue by ohordiichuk** [jingoro2112/wrench#23]
Hello,

on recent clang version:

```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

during `make` execution there are compilation errors, which could be easily by this patch. 

[patch.txt](https://github.com/user-attachments/files/15513515/patch.txt)

**Comment by jingoro2112** [comment]
Thank you for the patch, it should be part of the next update.

**Comment by jingoro2112** [comment]
patched
