### ISSUE TITLE
free() instead of g_free()?

### ISSUE THREAD

**Issue by khevessy** [jingoro2112/wrench#38]
After commit 76c5ced, when running `wr_compile()` for previously working code, we get a hard fault in the destructor of `WRstr` class, shouldn't be there g_free() instead of free()?
working: 	`~WRstr() { if ( m_str != m_smallbuf ) g_free(m_str); }`
not working: `~WRstr() { if ( m_str != m_smallbuf ) free(m_str); }`

**Comment by jingoro2112** [comment]
fixed this instance, and also a few others I had missed. I will be more careful going forward.

**Comment by khevessy** [comment]
Thanks!
