### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by darksotmoon** [jingoro2112/wrench#39]
WrenchPacket is allocated but never freed.

https://github.com/jingoro2112/wrench/blob/2f37ffa6bc24c2e017d37c5974ecac4174870512/discrete_src/debug/client_debug.cpp#L96

Is alloc a copy constructor? I can't work out why it is duplicating the packet.  This is the quick fix for me:

```
WrenchPacket * tx_packet = WrenchPacket::alloc(packet);
WrenchPacket *reply = transmit( tx_packet );
delete tx_packet;
```

**Comment by jingoro2112** [comment]
oops! thank you for pointing this out, obviously the debugger still has a lot of work to be done on it. fixed this in latest
