### ISSUE TITLE
Segfault instead of compilation error

### ISSUE THREAD

**Issue by Diegovsky** [jingoro2112/wrench#4]
Here's a snippet that causes a segfault using the wrench cli with `wrench r <scriptname>`:
```javascript
function print(arg) {
    log(arg == null)
    log(arg);
}

print("Hello, world!");
```

I wrote it accidentaly missing the semicolon but got a segfault instead of a compilation error. I tried debugging it with GDB and apparently it is something to do with `wr_callFunction` being called with zeroed `argv` and `argn`.

**Comment by jingoro2112** [comment]
well.. don't forget the semicolon! :)

I'll look into this right now

**Comment by Diegovsky** [comment]
Won't forget again :)

**Comment by jingoro2112** [comment]
That was a fun one. finally nailed it by comparing the expression resolves
actually completed to the list presented to the resolved. In the error case
they mismatch because the operators are not where they should be for a
valid expression.

fixed in latest, and thanks for the bugrep.

**Comment by Diegovsky** [comment]
No problem! I'm glad to help :+1:

**Comment by jingoro2112** [comment]
one thing though, there is no intrinsic "print" function.. I guess I should
add it to the default wrench cli. still it should just do nothing, not
segfault
